namespace: demo

replicaCount: 1

image:
  repository: node
  tag: 18-alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

config:
  APP_NAME: "node-helm-app"
  APP_ENV: "development"

secret:
  DB_USER: "admin"
  DB_PASSWORD: "supersecret"