{{- if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}-report
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: report
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              command: {{ toYaml .Values.cronjob.command | nindent 14 }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - configMapRef:
                    name: {{ .Chart.Name }}-config
                - secretRef:
                    name: {{ .Chart.Name }}-secret
{{- end }}